data:
  root: /work/06633/ylan/maverick2/data/dataset
  train_list: /work/06633/ylan/maverick2/data/dataset/112_dataset/train_list_T4T4RS1.txt
  test_list: /work/06633/ylan/maverick2/data/dataset/112_dataset/test_list_T4T4RS1.txt
  train_img_size: 192
  test_img_size: 192
  train_batch_size: 40
  test_batch_size: 40
  workers: 2
  rotate: 0
model:
  arch: resnet50
  num_classes: 7
  pretrained: '/home1/06633/ylan/.torch/models/resnet18-5c106cde.pth'
  ignore: ['fc.weight', 'fc.bias']
train:
  total_iter: 10000
  lr: 0.01
  lr_iters: [30,50]
  lr_gamma: 0.1
  momentum: 0.9
  weight_decay: 0.0001
loss:
#  pos_weight: [5.0, 5.0, 5.0, 5.0, 5.0]
  kpt_weight: 0.0
  cls_size_average: True
  kpt_size_average: True
  cls_loss: CE
use_kpt: False
epochs: 50
save_path: checkpoints/microscopy/unet_resnet18_192
save_freq: 1000
print_freq: 10
resume: False
