data:
  root: /work/06633/ylan/maverick2/data/dataset/dataset 
  train_list: /work/06633/ylan/maverick2/data/dataset/dataset/1600/ratio1.0/train_list.txt 
  test_list: /work/06633/ylan/maverick2/data/dataset/dataset/1600/ratio1.0/test_list.txt
  train_img_size: 1600 
  test_img_size: 1600 # output size
  train_batch_size: 2
  test_batch_size: 2
  workers: 0
  rotate: 0
  h_flip: True
  v_flip: True
  wavelet: False
  train_sampler_rate: 1.0
  valid_sampler_rate: 1.0
model:
  arch: unet_ode
  num_classes: 8 # with BG as a class
  dsr_list: [64, 32, 16]  # needs to match model.num_res
  dim_in: 1
  dim_latent : 64
  num_res: 3
  scale_factor: 2
  # pretrained: '/work/04776/chocks/maverick2/mseg/out/curated/odeunet_1600-4-4/1/valt_model_64_0.2806.pth'
  ignore: []  # ['fc.weight', 'fc.bias']
  load_optim: False
train:
  save_iter: 10
  lr: 0.01
  lr_iters: [50, 100, 150, 200, 250, 300, 350, 400, 450]
  lr_gamma: 0.7
  momentum: 0.99
  weight_decay: 0.0001
  warm_up: False
  warm_up_multiplier: 1
loss:
#  class_weight: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  # ['bg', 'PlasmaMembrane', 'NuclearMembrane', 'MitochondriaDark', 'MitochondriaLight', 'Desmosome',
  #            'Cytoskeleton', 'LipidDroplet']
  class_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  cls_size_average: True
  kpt_size_average: True
  cls_loss: CE
epochs: 500
#multi_stage: True
single_channel_target: False
save_path: /work/04776/chocks/maverick2/mseg/out/checkpoints/microscopy/1600-16/odesegnet
