data:
  root: ../extracted_data
  tiffroot: ../extracted_data
#  test_list: /work/06633/ylan/maverick2/data/dataset/1024_dataset/1024/S1/S1_Helios_1of3_v1
#  /S1_Helios_1of3_v1270_all_list.txt
#  slide_path: S1_Helios_1of3_v1270.tiff
#  slide_path: NA_T4_122117_11.tif
#  slide_name: NA_T4R_122117_19.tif
#  test_img_size: 64 # output size
  test_img_size: 512 # output size
  overlap_size: 480
  test_batch_size: 8
  workers: 4
  rotate: 0
  wavelet: False
  num_classes: 8
model:
  # arch: unet_ode
  arch: unet
  encoder: None
  dim_in: 1
  dim_latent : 32
  num_res: 4
  scale_factor: 4
  pretrained: ''
  ignore: ['fc.weight', 'fc.bias']
save_root: inference/
best_model: checkpoints/microscopy/512/bcediceloss/jjdz_model_192_0.4516.pth
inference: True
