data:
  root: /work/06633/ylan/maverick2/data/dataset/dataset
  train_list: /work/06633/ylan/maverick2/data/dataset/dataset/extracted_data/train_list.txt
  test_list: /work/06633/ylan/maverick2/data/dataset/dataset/extracted_data/test_list.txt
  train_img_size: 1280
  test_img_size: 1280 # output size
  train_batch_size: 1
  test_batch_size: 1
  workers: 0
  rotate: 0
  h_flip: True
  v_flip: True
model:
  arch: se_resnet50
  num_classes: 8 # with BG as a class
  pretrained: ''
  ignore: ['fc.weight', 'fc.bias']
train:
  total_iter: 10000
  lr: 0.1
  lr_iters: [23,33,43,53,63,73,83,93]
  lr_gamma: 0.01
  momentum: 0.99
  weight_decay: 0.0001
loss:
#  pos_weight: [5.0, 5.0, 5.0, 5.0, 5.0]
  kpt_weight: 0.0
  cls_size_average: True
  kpt_size_average: True
  cls_loss: CE
epochs: 100
single_channel_target: False
save_path: checkpoints/microscopy/whole_data
