data:
  root: /mnt/yushi/repo/UT/dataset
  train_list: /mnt/yushi/repo/UT/dataset/256/ratio1.0/train_list.txt
  test_list:  /mnt/yushi/repo/UT/dataset/256/ratio1.0/test_list.txt
  train_img_size: 256
  test_img_size: 256 # output size
  train_batch_size: 24
  test_batch_size: 32
  workers: 4
  rotate: 0
  h_flip: True
  v_flip: True
  wavelet: False
model:
  arch: unetplus
  encoder: None
  num_classes: 8 # with BG as a class
  pretrained: ''
  ignore: ['fc.weight', 'fc.bias']
train:
  lr: 0.01
  lr_iters: [40, 80, 120, 160, 200]
#  warm_up: 10
  lr_gamma: 0.5
  momentum: 0.99
  weight_decay: 0.0005
  save_iter: 10
loss:
#  class_weight: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  # ['bg', 'PlasmaMembrane', 'NuclearMembrane', 'MitochondriaDark', 'MitochondriaLight', 'Desmosome',
  #            'Cytoskeleton', 'LipidDroplet']
  class_weight: [1.0, 10.0, 10.0, 1.0, 1.0, 10.0, 1.0, 10.0]
  cls_size_average: True
  kpt_size_average: True
  cls_loss: CE
epochs: 200
single_channel_target: False
save_path: checkpoints/microscopy/256/randomcrop
