data:
  root: /mnt/yushi/repo/UT/dataset
  tiffroot: /mnt/yushi/repo/UT/extracted_data
  train_list: /mnt/yushi/repo/UT/dataset/512/ratio1.0/train_list.txt
  test_list:  /mnt/yushi/repo/UT/dataset/512/ratio1.0/test_list.txt
  train_img_size: 512
  test_img_size: 512 # output size
  train_batch_size: 12
  test_batch_size: 32
  workers: 4
  rotate: 0
  h_flip: True
  v_flip: True
  wavelet: False
model:
  arch: unet
  encoder: None
  num_classes: 8 # with BG as a class
  pretrained: ''
  ignore: ['fc.weight', 'fc.bias']
train:
  lr: 0.001
  lr_iters: [30, 60, 90, 120, 160]
#  warm_up: 10
  lr_gamma: 0.5
  momentum: 0.99
  weight_decay: 0.0005
  save_iter: 10
loss:
#  class_weight: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
  # ['bg', 'PlasmaMembrane', 'NuclearMembrane', 'MitochondriaDark', 'MitochondriaLight', 'Desmosome',
  #            'Cytoskeleton', 'LipidDroplet']
  class_weight: [0.5, 10.0, 10.0, 1.0, 1.0, 10.0, 1.0, 10.0]
  cls_size_average: True
  kpt_size_average: True
  cls_loss: bcediceloss
epochs: 200
save_path: checkpoints/microscopy/512/bcediceloss
